name: terraform-iam-vars

on:
  push:
    branches: [ "main" ]
    paths: [ "iam/**", ".github/workflows/terraform-iam-vars.yml" ]
  pull_request:
    branches: [ "main" ]
    paths: [ "iam/**", ".github/workflows/terraform-iam-vars.yml" ]

permissions:
  contents: read

env:
  TF_VERSION: "1.6.6"
  WORKDIR: iam
  AWS_REGION: "us-east-1"   # or set as repo Variable and keep this line

jobs:
  apply:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    env:
      AKI: ${{ vars.AWS_ACCESS_KEY_ID }}
      SAK: ${{ vars.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v4

      - name: Validate repo variables
        run: |
          set -euo pipefail
          [ -n "${AKI:-}" ] || { echo "Missing repo variable AWS_ACCESS_KEY_ID"; exit 1; }
          [ -n "${SAK:-}" ] || { echo "Missing repo variable AWS_SECRET_ACCESS_KEY"; exit 1; }
          [ -n "${AWS_REGION:-}" ] || { echo "Missing AWS_REGION (env or Variable)"; exit 1; }

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ env.AKI }}
          aws-secret-access-key: ${{ env.SAK }}
          aws-region:            ${{ env.AWS_REGION }}

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - run: terraform init -input=false
        working-directory: ${{ env.WORKDIR }}

      - run: terraform apply -input=false -auto-approve
        working-directory: ${{ env.WORKDIR }}

  plan:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    env:
      AKI: ${{ vars.AWS_ACCESS_KEY_ID }}
      SAK: ${{ vars.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v4

      - name: Validate repo variables
        run: |
          set -euo pipefail
          [ -n "${AKI:-}" ] || { echo "Missing repo variable AWS_ACCESS_KEY_ID"; exit 1; }
          [ -n "${SAK:-}" ] || { echo "Missing repo variable AWS_SECRET_ACCESS_KEY"; exit 1; }
          [ -n "${AWS_REGION:-}" ] || { echo "Missing AWS_REGION (env or Variable)"; exit 1; }

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ env.AKI }}
          aws-secret-access-key: ${{ env.SAK }}
          aws-region:            ${{ env.AWS_REGION }}

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - run: terraform fmt -check -recursive
        working-directory: ${{ env.WORKDIR }}

      - run: terraform init -input=false
        working-directory: ${{ env.WORKDIR }}

      - run: terraform validate -no-color
        working-directory: ${{ env.WORKDIR }}

      - run: terraform plan -input=false -no-color -out=tfplan
        working-directory: ${{ env.WORKDIR }}
