name: terraform-s3

on:
  push:
    branches: [ "main" ]
    paths: [ "s3/**", ".github/workflows/terraform-s3.yml" ]
  pull_request:
    branches: [ "main" ]
    paths: [ "s3/**", ".github/workflows/terraform-s3.yml" ]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
  id-token: write

concurrency:
  group: terraform-s3-${{ github.ref }}
  cancel-in-progress: true

env:
  TF_VERSION: "1.6.6"
  WORKDIR: s3
  AWS_REGION: "us-east-1"   # change if needed

jobs:
  plan:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Prefer Secrets; falls back to Variables if you kept them there
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID != '' && secrets.AWS_ACCESS_KEY_ID || vars.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY != '' && secrets.AWS_SECRET_ACCESS_KEY || vars.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ env.AWS_REGION }}

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Cache Terraform plugins
        uses: actions/cache@v4
        with:
          path: ~/.terraform.d/plugin-cache
          key: ${{ runner.os }}-tf-${{ hashFiles('s3/.terraform.lock.hcl') }}
          restore-keys: |
            ${{ runner.os }}-tf-

      - name: Terraform fmt
        working-directory: ${{ env.WORKDIR }}
        run: terraform fmt -check -recursive

      - name: Terraform init
        working-directory: ${{ env.WORKDIR }}
        run: terraform init -input=false

      - name: Terraform validate
        working-directory: ${{ env.WORKDIR }}
        run: terraform validate -no-color

      - name: Terraform plan
        working-directory: ${{ env.WORKDIR }}
        run: terraform plan -input=false -no-color -out=tfplan

      - name: Upload plan
        uses: actions/upload-artifact@v4
        with:
          name: s3-tfplan
          path: s3/tfplan

  apply:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID != '' && secrets.AWS_ACCESS_KEY_ID || vars.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY != '' && secrets.AWS_SECRET_ACCESS_KEY || vars.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ env.AWS_REGION }}

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform init
        working-directory: ${{ env.WORKDIR }}
        run: terraform init -input=false

      - name: Terraform apply
        working-directory: ${{ env.WORKDIR }}
        run: terraform apply -input=false -auto-approve

      - name: Show outputs
        working-directory: ${{ env.WORKDIR }}
        run: |
          echo "### Terraform Outputs" >> $GITHUB_STEP_SUMMARY
          terraform output -json | jq -r 'to_entries[] | "- **\(.key)**: \(.value.value)"' >> $GITHUB_STEP_SUMMARY
